#!/bin/bash

DEBUG="0"
if [ "$1" == "-d" ] ; then 
	DEBUG="1"
        shift
fi
if [ -z "$1" ] ; then
   echo "Need uri of shar script"
   exit 1
else
   URI=$1
fi
if [ "$DEBUG" == "1" ] ; then
   set -x
fi
FN=$(basename $URI)
echo Installer: $FN
wget $URI -O /tmp/$FN >/tmp/log 2>&1
if [ $? -ne 0 ] ; then
   cat /tmp/log 1>&2
   exit 1
fi
chmod 755 /tmp/$FN
yes | /tmp/$FN -nogui -e /tmp/foo -l /tmp/montavista  >/tmp/log 2>&1
if [ $? -ne 0 ] ; then
   cat /tmp/log 1>&2
fi
/lice-kill /tmp/montavista/ 2>/dev/null || true
/getVersioning /tmp/montavista/
rm /tmp/* -rf

