#!/bin/bash

set -e
set -x
if [ -z "$1" ] ; then
   echo "Need uri of shar script"
   exit 1
else
   URI=$1
fi

FN=$(basename $URI)
echo Installer: $FN
wget $URI -O $FN >/log 2>&1
if [ $? -ne 0 ] ; then
   cat /out/log
   exit 1
fi
chmod 755 $FN
yes | ./$FN -nogui -e /out/foo -l /out/montavista  >/out/log 2>&1
if [ $? -ne 0 ] ; then
   cat /out/log
   exit 1
fi
/lice-kill /out/montavista/ 2>/dev/null || true
/getVersioning /out/montavista/
rm /out/* -rf

