#!/bin/bash

if [ -z "$1" ] ; then
   echo "Need install location"
   exit 1
fi

install=$1

echo -n "Integration Platform : "
chmod 755 $1/montavista/bin/*
$1/montavista/bin/mvl-fetch --version | while read A B; do echo $B; done
BIN=$(ls $1/montavista/tools/*/bin/*-gcc*)
chmod 755 $BIN
GCC=$($(ls $1/montavista/tools/*/bin/*-gcc | head -n 1) --version | head -n 1)
LEN=$(echo $GCC | cut -d ")" -f 1 | wc -w)
echo -n "Toolchain            : "
echo $GCC | cut -d ")" -f 1 | cut -d " " -f $(expr $LEN)
echo -n "Devrocket            : "
grep version $1/features/com.mvista.devtools.devrocket.*/feature.xml | cut -d : -f 2 | head -n 2 | tail -n 1 | cut -d '"' -f 2

